### PR TITLE
Add ranger_audits AVRO schema file and nifi template file

### PR DESCRIPTION
**Pull request by rogerding**
Add ranger_audits AVRO schema file and nifi template file which queries Solr to get ranger audit event, process them and send to Syslog

### CODE REVIEW

**Comment by tmgstevens** [comment]
@rogerding  please could you sign this commit?

**Comment by Chaffelson** [comment]
@rogerding is this pathed to blogs/ranger_audit_nifi, or off the root? hard to tell from the commit file listing.

**Comment by rogerding** [comment]
@Chaffelson path off the root

**Comment by Chaffelson** [comment]
> @Chaffelson path off the root

Ok, I believe this is for a blog so please put it under the blogs folder.

**Pull request closed without merging**
